modLoader = "javafml"
loaderVersion = "[4,)"
displayURL = "https://github.com/HappyRespawnanchor/dyeable_shulkers/issues"
issueTrackerURL = "https://github.com/HappyRespawnanchor/dyeable_shulkers/issues"
license = "CC0-1.0"

[[mods]]
modId = "dyeable_shulkers"
version = "${version}"
displayName = "Dyeable Shulkers"
authors = "HappyRespawnanchor"
description = '''
Dye your Shulkers!
'''
#logoFile = ""

[[dependencies.dyeable_shulkers]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dyeable_shulkers]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
